# Generated by Django 2.0.2 on 2018-02-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('content', models.TextField(null=True, verbose_name='content')),
                ('authors', models.TextField(null=True, verbose_name='authors')),
                ('url', models.URLField(null=True, verbose_name='url')),
            ],
        ),
    ]
