# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factcoin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
