# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factcoin', '0002_document_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='datetime',
        ),
    ]
