# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factcoin', '0004_auto_20180217_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('document1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='factcoin.Document')),
                ('document2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='factcoin.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='factcoin.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='factcoin.Document')),
            ],
        ),
    ]
