# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factcoin', '0006_document_raw_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='factcoin.Document'),
        ),
    ]
