# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factcoin', '0008_auto_20180218_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='factcoin.Document'),
        ),
    ]
