# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factcoin', '0009_auto_20180218_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='factcoin.Document'),
        ),
    ]
