version: '2'
services:
  postgres:
    image: postgres
    restart: on-failure
  redis:
    image: redis:alpine
    restart: on-failure
  elasticsearch:
    image: "elasticsearch:2.4-alpine"
    restart: on-failure
    ports:
      - "9200:9200"
  factcoin:
    image: factcoin
    links:
      - postgres
      - redis
      - elasticsearch
    ports:
      - "2233:22"
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - "POSTGRES_PORT_5432_TCP_PORT=5432"
      - "POSTGRES_PORT_5432_TCP_ADDR=postgres"
      - "DJANGO_SETTINGS_MODULE=factcoin.settings.local"
      - "BONSAI_URL=http://elasticsearch:9200/"
      - "ELASTIC_USERNAME=elastic"
      - "ELASTIC_PASSWORD=changeme"
    volumes:
      - $PWD/templates:/app/templates
      - $PWD/factcoin:/app/factcoin
      - $PWD/shared:/app/shared
      - $PWD/static/js:/app/static/js
      - $PWD/static/css:/app/static/css
    restart: on-failure
